// mockT.js — clés de traduction pour le snack RGPD
// Copie fidèle des clés RGPD de LIXUM-APP/src/pages/profile/profileConstants.js
// + quelques clés visuelles pour ProfilePageMock (header, sections, stats).

export var T = {
  fr: {
    // === Visuel ProfilePageMock ===
    profileTitle: 'Mon profil',
    profileSubscription: 'Abonnement',
    profileNotifications: 'Notifications',
    profileLanguage: 'Langue',
    profilePreferences: 'Préférences',
    profileLogout: 'Se déconnecter',
    profileDeleteAccount: 'Supprimer mon compte',
    profileStatsTitle: 'STATISTIQUES',
    profileSettingsTitle: 'PARAMÈTRES',
    profileAccountTitle: 'COMPTE',
    profileStatXp: 'XP total',
    profileStatLix: 'Lix',
    profileStatLevel: 'Niveau',
    // === DeleteAccountModal ===
    deleteAccountTitle: 'Supprimer mon compte',
    deleteAccountWarning: '⚠ Cette action est irréversible. Toutes vos données (Nutrition, Activité, Santé, Social) seront définitivement supprimées après 30 jours. Vous pouvez changer d\'avis en vous reconnectant dans ce délai.',
    deleteReasonSectionTitle: 'Pourquoi partez-vous ? (optionnel)',
    deleteReasonNoLongerUse: 'Je n\'utilise plus l\'app',
    deleteReasonTooExpensive: 'Abonnement trop cher',
    deleteReasonTooComplex: 'App trop compliquée',
    deleteReasonBugs: 'Bugs / Problèmes techniques',
    deleteReasonPrivacy: 'Protection de ma vie privée',
    deleteReasonOther: 'Autre',
    deleteReasonOtherPlaceholder: 'Précisez votre raison...',
    deleteConfirmSectionTitle: 'Confirmation finale',
    deleteConfirmLabel: 'Tapez SUPPRIMER pour activer le bouton',
    deleteConfirmPlaceholder: 'SUPPRIMER',
    deleteConfirmButton: 'Supprimer définitivement',
    deleteConfirmCountdown: 'Appuyez dans {s}s...',
    deleteCancelButton: 'Annuler',
    deleteAdminBlocked: 'Les comptes administrateur ne peuvent pas être supprimés.',
    deleteGenericError: 'Erreur lors de la demande de suppression.',
    // === AccountDeletedSuccessScreen ===
    deleteSuccessScreenTitle: 'Compte programmé pour suppression',
    deleteSuccessScreenBody: 'Votre compte sera définitivement supprimé le {date}.\nVous pouvez changer d\'avis en vous reconnectant avant cette date.',
    deleteSuccessScreenHint: 'Un email de confirmation vous sera envoyé.',
    deleteSuccessScreenButton: 'J\'ai compris',
    // === RestoreAccountModal ===
    restoreModalTitle: 'Votre compte est programmé pour suppression',
    restoreModalBody: 'Suppression prévue le {date}. Voulez-vous restaurer votre compte LIXUM ?',
    restoreDaysLeft: '{n} jours restants',
    restoreDayLeftSingular: '{n} jour restant',
    restoreConfirmButton: 'Restaurer mon compte',
    restoreRejectButton: 'Confirmer la suppression',
    restoreRejectDoubleConfirmTitle: 'Êtes-vous absolument certain ?',
    restoreRejectDoubleConfirmBody: 'Cette fois c\'est définitif. Votre compte sera supprimé le {date}. Vous ne pourrez plus le restaurer.',
    restoreRejectDoubleConfirmButton: 'Oui, supprimer définitivement',
    restoreRejectCancel: 'Non, je réfléchis',
    restoreSuccessTitle: 'Bienvenue à nouveau !',
    restoreSuccessBody: 'Votre compte a été restauré avec succès.',
    restoreGenericError: 'Erreur lors de la restauration. Réessayez.'
  },
  en: {
    // === Visual ProfilePageMock ===
    profileTitle: 'My profile',
    profileSubscription: 'Subscription',
    profileNotifications: 'Notifications',
    profileLanguage: 'Language',
    profilePreferences: 'Preferences',
    profileLogout: 'Log out',
    profileDeleteAccount: 'Delete my account',
    profileStatsTitle: 'STATISTICS',
    profileSettingsTitle: 'SETTINGS',
    profileAccountTitle: 'ACCOUNT',
    profileStatXp: 'Total XP',
    profileStatLix: 'Lix',
    profileStatLevel: 'Level',
    // === DeleteAccountModal ===
    deleteAccountTitle: 'Delete my account',
    deleteAccountWarning: '⚠ This action is irreversible. All your data (Nutrition, Activity, Health, Social) will be permanently deleted after 30 days. You can change your mind by logging back in before then.',
    deleteReasonSectionTitle: 'Why are you leaving? (optional)',
    deleteReasonNoLongerUse: 'I no longer use the app',
    deleteReasonTooExpensive: 'Subscription too expensive',
    deleteReasonTooComplex: 'App too complicated',
    deleteReasonBugs: 'Bugs / Technical issues',
    deleteReasonPrivacy: 'Privacy protection',
    deleteReasonOther: 'Other',
    deleteReasonOtherPlaceholder: 'Please specify...',
    deleteConfirmSectionTitle: 'Final confirmation',
    deleteConfirmLabel: 'Type DELETE to enable the button',
    deleteConfirmPlaceholder: 'DELETE',
    deleteConfirmButton: 'Delete permanently',
    deleteConfirmCountdown: 'Press in {s}s...',
    deleteCancelButton: 'Cancel',
    deleteAdminBlocked: 'Administrator accounts cannot be deleted.',
    deleteGenericError: 'Error requesting deletion.',
    // === AccountDeletedSuccessScreen ===
    deleteSuccessScreenTitle: 'Account scheduled for deletion',
    deleteSuccessScreenBody: 'Your account will be permanently deleted on {date}.\nYou can change your mind by logging back in before then.',
    deleteSuccessScreenHint: 'A confirmation email will be sent to you.',
    deleteSuccessScreenButton: 'I understand',
    // === RestoreAccountModal ===
    restoreModalTitle: 'Your account is scheduled for deletion',
    restoreModalBody: 'Deletion scheduled for {date}. Would you like to restore your LIXUM account?',
    restoreDaysLeft: '{n} days left',
    restoreDayLeftSingular: '{n} day left',
    restoreConfirmButton: 'Restore my account',
    restoreRejectButton: 'Confirm deletion',
    restoreRejectDoubleConfirmTitle: 'Are you absolutely sure?',
    restoreRejectDoubleConfirmBody: 'This time it\'s final. Your account will be deleted on {date}. You won\'t be able to restore it.',
    restoreRejectDoubleConfirmButton: 'Yes, delete permanently',
    restoreRejectCancel: 'No, let me think',
    restoreSuccessTitle: 'Welcome back!',
    restoreSuccessBody: 'Your account has been successfully restored.',
    restoreGenericError: 'Error restoring account. Try again.'
  }
};
