// mockT.js — clés de traduction pour le snack RGPD
// Copie fidèle des clés RGPD de LIXUM-APP/src/pages/profile/profileConstants.js
// + quelques clés visuelles pour ProfilePageMock (header, sections, stats).

export var T = {
  fr: {
    // === Cles ProfilePage prod (clonage 100%) ===
    personalData: 'DONNÉES PERSONNELLES',
    age: 'Âge',
    weight: 'Poids',
    height: 'Taille',
    bmi: 'IMC',
    years: 'ans',
    kg: 'kg',
    cm: 'cm',
    editProfile: 'Modifier mon profil',
    settings: 'PARAMÈTRES',
    connectors: 'CONNECTEURS',
    location: 'Ma localisation',
    locationSub: 'Pour les recommandations ALIXEN',
    subscription: 'Mon abonnement',
    subscriptionSub: 'Gérer, changer ou résilier',
    notifications: 'Notifications',
    notifSub: 'Rappels médicaments, analyses',
    learn: 'APPRENDRE',
    glossary: 'Comprendre les termes',
    glossarySub: 'BMR, TDEE, Macros, IMC...',
    guide: 'Guide LIXUM',
    guideSub: 'Toutes les fonctionnalités',
    legal: 'LÉGAL & SUPPORT',
    privacy: 'Politique de confidentialité',
    terms: 'Termes et conditions',
    contact: 'Nous contacter',
    rate: 'Évaluer LIXUM',
    logout: 'Se déconnecter',
    logoutConfirm: 'Es-tu sûr ?',
    cancel: 'Annuler',
    notDefined: 'Non définie',
    free: 'Gratuit',
    madeWith: 'Fait avec ❤️ au Burundi',
    connect: 'Connecter',
    disconnect: 'Déconnecter',
    comingSoon: 'Bientôt',
    connectorsDesc: 'Synchronisez vos montres et apps de santé',
    // === Visuel ProfilePageMock (extras) ===
    profileTitle: 'Mon profil',
    profileSubscription: 'Abonnement',
    profileNotifications: 'Notifications',
    profileLanguage: 'Langue',
    profilePreferences: 'Préférences',
    profileLogout: 'Se déconnecter',
    profileDeleteAccount: 'Supprimer mon compte',
    profileStatsTitle: 'STATISTIQUES',
    profileSettingsTitle: 'PARAMÈTRES',
    profileAccountTitle: 'COMPTE',
    profileStatXp: 'XP total',
    profileStatLix: 'Lix',
    profileStatLevel: 'Niveau',
    // === DeleteAccountModal ===
    deleteAccountTitle: 'Supprimer mon compte',
    deleteAccountWarning: '⚠ Cette action est irréversible. Toutes vos données (Nutrition, Activité, Santé, Social) seront définitivement supprimées après 30 jours. Vous pouvez changer d\'avis en vous reconnectant dans ce délai.',
    deleteReasonSectionTitle: 'Pourquoi partez-vous ? (optionnel)',
    deleteReasonNoLongerUse: 'Je n\'utilise plus l\'app',
    deleteReasonTooExpensive: 'Abonnement trop cher',
    deleteReasonTooComplex: 'App trop compliquée',
    deleteReasonBugs: 'Bugs / Problèmes techniques',
    deleteReasonPrivacy: 'Protection de ma vie privée',
    deleteReasonOther: 'Autre',
    deleteReasonOtherPlaceholder: 'Précisez votre raison...',
    deleteConfirmSectionTitle: 'Confirmation finale',
    deleteConfirmLabel: 'Tapez SUPPRIMER pour activer le bouton',
    deleteConfirmPlaceholder: 'SUPPRIMER',
    deleteConfirmButton: 'Supprimer définitivement',
    deleteConfirmCountdown: 'Appuyez dans {s}s...',
    deleteCancelButton: 'Annuler',
    deleteAdminBlocked: 'Les comptes administrateur ne peuvent pas être supprimés.',
    deleteGenericError: 'Erreur lors de la demande de suppression.',
    // === AccountDeletedSuccessScreen ===
    deleteSuccessScreenTitle: 'Compte programmé pour suppression',
    deleteSuccessScreenBody: 'Votre compte sera définitivement supprimé le {date}.\nVous pouvez changer d\'avis en vous reconnectant avant cette date.',
    deleteSuccessScreenHint: 'Un email de confirmation vous sera envoyé.',
    deleteSuccessScreenButton: 'J\'ai compris',
    // === RestoreAccountModal ===
    restoreModalTitle: 'Votre compte est programmé pour suppression',
    restoreModalBody: 'Suppression prévue le {date}. Voulez-vous restaurer votre compte LIXUM ?',
    restoreDaysLeft: '{n} jours restants',
    restoreDayLeftSingular: '{n} jour restant',
    restoreConfirmButton: 'Restaurer mon compte',
    restoreRejectButton: 'Confirmer la suppression',
    restoreRejectDoubleConfirmTitle: 'Êtes-vous absolument certain ?',
    restoreRejectDoubleConfirmBody: 'Cette fois c\'est définitif. Votre compte sera supprimé le {date}. Vous ne pourrez plus le restaurer.',
    restoreRejectDoubleConfirmButton: 'Oui, supprimer définitivement',
    restoreRejectCancel: 'Non, je réfléchis',
    restoreSuccessTitle: 'Bienvenue à nouveau !',
    restoreSuccessBody: 'Votre compte a été restauré avec succès.',
    restoreGenericError: 'Erreur lors de la restauration. Réessayez.',
    restoreDaysLeftWarning: '{n} jours restants',
    restoreDaysLeftCritical: '{n} jours restants — urgent !',
    restoreCheckingAccount: 'Vérification du compte...',
    restoreInProgress: 'Restauration en cours...',
    restoreAlmostReady: 'Presque prêt...',
    bannerDeletionPending: '⏱ Compte programmé pour suppression dans {days} jours',
    bannerDeletionPendingUrgent: '⚠ Compte sera supprimé dans {days} jour(s) — Restaurer maintenant',
    bannerRestoreLink: 'Restaurer',
    editProfileTitle: 'Modifier mon profil',
    editProfileSubtitle: 'Vos donnees sont privees et chiffrees',
    editProfileSectionIdentity: 'IDENTITE',
    editProfileSectionBody: 'CORPS',
    editProfileSectionLocation: 'LOCALISATION',
    editProfileLabelName: 'Comment vous appeler',
    editProfileCaptionName: 'Visible uniquement par vous',
    editProfileLabelAge: 'Age',
    editProfileLabelWeight: 'Poids',
    editProfileLabelHeight: 'Taille',
    editProfileLabelCity: 'Ville',
    editProfilePlaceholderName: 'Votre prenom',
    editProfilePlaceholderCity: 'Votre ville',
    editProfileImcLabel: 'IMC',
    editProfileImcUnderweight: 'Maigreur',
    editProfileImcNormal: 'Normal',
    editProfileImcOverweight: 'Surpoids',
    editProfileImcObese: 'Obesite',
    editProfileCancelButton: 'Annuler',
    editProfileSaveButton: 'Enregistrer',
    editProfileSaveSuccess: 'Profil mis a jour',
    editProfileSaveError: 'Erreur de sauvegarde',
    editProfileNameEmpty: 'Le prenom est requis'
  },
  en: {
    // === Cles ProfilePage prod (clonage 100%) ===
    personalData: 'PERSONAL DATA',
    age: 'Age',
    weight: 'Weight',
    height: 'Height',
    bmi: 'BMI',
    years: 'yrs',
    kg: 'kg',
    cm: 'cm',
    editProfile: 'Edit my profile',
    settings: 'SETTINGS',
    connectors: 'CONNECTORS',
    location: 'My location',
    locationSub: 'For ALIXEN recommendations',
    subscription: 'My subscription',
    subscriptionSub: 'Manage, change or cancel',
    notifications: 'Notifications',
    notifSub: 'Medication, test reminders',
    learn: 'LEARN',
    glossary: 'Understand the terms',
    glossarySub: 'BMR, TDEE, Macros, BMI...',
    guide: 'LIXUM Guide',
    guideSub: 'All features',
    legal: 'LEGAL & SUPPORT',
    privacy: 'Privacy policy',
    terms: 'Terms and conditions',
    contact: 'Contact us',
    rate: 'Rate LIXUM',
    logout: 'Log out',
    logoutConfirm: 'Are you sure?',
    cancel: 'Cancel',
    notDefined: 'Not set',
    free: 'Free',
    madeWith: 'Made with ❤️ in Burundi',
    connect: 'Connect',
    disconnect: 'Disconnect',
    comingSoon: 'Soon',
    connectorsDesc: 'Sync your watches and health apps',
    // === Visual ProfilePageMock (extras) ===
    profileTitle: 'My profile',
    profileSubscription: 'Subscription',
    profileNotifications: 'Notifications',
    profileLanguage: 'Language',
    profilePreferences: 'Preferences',
    profileLogout: 'Log out',
    profileDeleteAccount: 'Delete my account',
    profileStatsTitle: 'STATISTICS',
    profileSettingsTitle: 'SETTINGS',
    profileAccountTitle: 'ACCOUNT',
    profileStatXp: 'Total XP',
    profileStatLix: 'Lix',
    profileStatLevel: 'Level',
    // === DeleteAccountModal ===
    deleteAccountTitle: 'Delete my account',
    deleteAccountWarning: '⚠ This action is irreversible. All your data (Nutrition, Activity, Health, Social) will be permanently deleted after 30 days. You can change your mind by logging back in before then.',
    deleteReasonSectionTitle: 'Why are you leaving? (optional)',
    deleteReasonNoLongerUse: 'I no longer use the app',
    deleteReasonTooExpensive: 'Subscription too expensive',
    deleteReasonTooComplex: 'App too complicated',
    deleteReasonBugs: 'Bugs / Technical issues',
    deleteReasonPrivacy: 'Privacy protection',
    deleteReasonOther: 'Other',
    deleteReasonOtherPlaceholder: 'Please specify...',
    deleteConfirmSectionTitle: 'Final confirmation',
    deleteConfirmLabel: 'Type DELETE to enable the button',
    deleteConfirmPlaceholder: 'DELETE',
    deleteConfirmButton: 'Delete permanently',
    deleteConfirmCountdown: 'Press in {s}s...',
    deleteCancelButton: 'Cancel',
    deleteAdminBlocked: 'Administrator accounts cannot be deleted.',
    deleteGenericError: 'Error requesting deletion.',
    // === AccountDeletedSuccessScreen ===
    deleteSuccessScreenTitle: 'Account scheduled for deletion',
    deleteSuccessScreenBody: 'Your account will be permanently deleted on {date}.\nYou can change your mind by logging back in before then.',
    deleteSuccessScreenHint: 'A confirmation email will be sent to you.',
    deleteSuccessScreenButton: 'I understand',
    // === RestoreAccountModal ===
    restoreModalTitle: 'Your account is scheduled for deletion',
    restoreModalBody: 'Deletion scheduled for {date}. Would you like to restore your LIXUM account?',
    restoreDaysLeft: '{n} days left',
    restoreDayLeftSingular: '{n} day left',
    restoreConfirmButton: 'Restore my account',
    restoreRejectButton: 'Confirm deletion',
    restoreRejectDoubleConfirmTitle: 'Are you absolutely sure?',
    restoreRejectDoubleConfirmBody: 'This time it\'s final. Your account will be deleted on {date}. You won\'t be able to restore it.',
    restoreRejectDoubleConfirmButton: 'Yes, delete permanently',
    restoreRejectCancel: 'No, let me think',
    restoreSuccessTitle: 'Welcome back!',
    restoreSuccessBody: 'Your account has been successfully restored.',
    restoreGenericError: 'Error restoring account. Try again.',
    restoreDaysLeftWarning: '{n} days left',
    restoreDaysLeftCritical: '{n} days left — urgent!',
    restoreCheckingAccount: 'Checking account...',
    restoreInProgress: 'Restoring your account...',
    restoreAlmostReady: 'Almost ready...',
    bannerDeletionPending: '⏱ Account scheduled for deletion in {days} days',
    bannerDeletionPendingUrgent: '⚠ Account will be deleted in {days} day(s) — Restore now',
    bannerRestoreLink: 'Restore',
    editProfileTitle: 'Edit my profile',
    editProfileSubtitle: 'Your data is private and encrypted',
    editProfileSectionIdentity: 'IDENTITY',
    editProfileSectionBody: 'BODY',
    editProfileSectionLocation: 'LOCATION',
    editProfileLabelName: 'How should we call you',
    editProfileCaptionName: 'Visible only by you',
    editProfileLabelAge: 'Age',
    editProfileLabelWeight: 'Weight',
    editProfileLabelHeight: 'Height',
    editProfileLabelCity: 'City',
    editProfilePlaceholderName: 'Your first name',
    editProfilePlaceholderCity: 'Your city',
    editProfileImcLabel: 'BMI',
    editProfileImcUnderweight: 'Underweight',
    editProfileImcNormal: 'Normal',
    editProfileImcOverweight: 'Overweight',
    editProfileImcObese: 'Obesity',
    editProfileCancelButton: 'Cancel',
    editProfileSaveButton: 'Save',
    editProfileSaveSuccess: 'Profile updated',
    editProfileSaveError: 'Save error',
    editProfileNameEmpty: 'First name is required'
  }
};
